Orbelite.Erp.SitioWeb/Controllers/Admin/AuthController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Orbelite.Erp.Servicios.Admin.Auth.Usuarios.Dtos;
using Orbelite.Erp.Servicios.Auth.Usuarios.Servicios.Abstracciones;
using Orbelite.Principal.Comunes.Infraestructura.Dtos;
using Orbelite.Principal.Seguridad.Datos.Repositorios.Abstracciones;
using Orbelite.Principal.Seguridad.Servicios.Auth.Servicios.Abstracciones;
using Orbelite.Principal.Seguridad.Servicios.General.Dtos;
using Orbelite.Principal.Seguridad.Servicios.Peticiones.Servicios.Abstracciones;
using Orbelite.Principal.WebComunes.ApiWeb.Auth.Atributos;
using Orbelite.Principal.WebComunes.WebSite.Auth;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Orbelite.Erp.SitioWeb.Controllers.Admin
{
    [Route("api/admin/[controller]")]
    [ApiController]
    public class AuthController : ControladorAuth
    {
        private readonly UrlConfiguracionDto _urlConfiguracionDto;
        private readonly SeguridadConfiguracionDto _seguridadConfiguracionDto;
        private readonly IPeticionServicio _peticionServicio;
        private readonly IPersonaRepositorio _personaRepositorio;
        private readonly ILoginServicio _loginServicio;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly IRecuperarContraseniaServicio _recuperarContraseniaServicio;

        public AuthController(IOptionsMonitor<CookieAuthenticationOptions> optionsMonitor,
            UrlConfiguracionDto urlConfiguracionDto,
            SeguridadConfiguracionDto seguridadConfiguracionDto,
            IPeticionServicio peticionServicio,
            IPersonaRepositorio personaRepositorio,
            ILoginServicio loginServicio,
            IWebHostEnvironment hostingEnvironment,
            IRecuperarContraseniaServicio recuperarContraseniaServicio
            ) : base(optionsMonitor)
        {
            _urlConfiguracionDto = urlConfiguracionDto;
            _seguridadConfiguracionDto = seguridadConfiguracionDto;
            _peticionServicio = peticionServicio;
            _personaRepositorio = personaRepositorio;
            _loginServicio = loginServicio;
            _hostingEnvironment = hostingEnvironment;
            _recuperarContraseniaServicio = recuperarContraseniaServicio;
        }


        [HttpPost("OlvidoContrasenia")]
        public async Task<RespuestaSimpleDto<bool>> OlvidoContrasenia([FromBody] RecuperarContraseniaDto peticion)
        {
            peticion.Plantilla = $"{_hostingEnvironment.WebRootPath}\\archivos\\htmlRecuperarContrasenia.html";
            var operacion = await _recuperarContraseniaServicio.EnviarCorreoRecuperarContrasenia(peticion);
            return ObtenerResultadoOGenerarErrorDeOperacion(operacion);
        }


        [HttpGet("Crediticio/{dni}")]
        [RequiereAcceso]
        public IActionResult Crediticio(string dni)
        {
            var cabecera = new Dictionary<string, string>();
            cabecera.Add("app-name", _seguridadConfiguracionDto.AppName);
            var peticion = _peticionServicio.RealizarJsonPost($"{_urlConfiguracionDto.UrlApiFuentes}api/persona/consultas/Sbs/Consultar", new { Documento = dni, Tipo = 100 }, ObtenerIdUsuarioActual() ?? 0, cabecera);
            return ObtenerResultadoOGenerarErrorDeSimpleRespuestaPeticionWebDto(peticion);
        }

        [HttpPost("Tansacciones")]
        [RequiereAcceso]
        public IActionResult Tansacciones()
        {
            var peticion = _peticionServicio.RealizarJsonPost($"{_urlConfiguracionDto.UrlSmkt}api/Transaccion/TransaccionesPorAgente", new { Pagina = 1, TamanioPagina = 10 }, ObtenerIdUsuarioActual() ?? 0);
            return ObtenerResultadoOGenerarErrorDeSimpleRespuestaPeticionWebDto(peticion);
        }

        [HttpGet("LoginAplicacion/{token}")]
        public async Task<ActionResult> LoginAplicacion(string token)
        {
            try
            {
                var operacion = await LoginApp(token);
                if (operacion.Suceso)
                {
                    return RedirectToPage("/Admin/Index");
                }
            }
            catch
            { }
            return RedirectToPage("/Admin/Login");
        }

        [HttpGet("AppIbroker")]
        [RequiereAcceso]
        public async Task<ActionResult> AppIbroker()
        {
            var operacion = await _loginServicio.ObtenerTokenSesionApp(ObtenerIdUsuarioActual() ?? 0);
            return Redirect($"{_urlConfiguracionDto.UrlIbroker}api/admin/Auth/AppIbroker/{operacion.Resultado.Id}");
        }

        //[HttpGet("AppInfraxion")]
        //[RequiereAcceso]
        //public async Task<ActionResult> AppInfraxion()
        //{
        //    var operacion = await _loginServicio.ObtenerTokenSesionApp(ObtenerIdUsuarioActual() ?? 0);
        //    return Redirect($"{_urlConfiguracionDto.UrlInfraxion}Auth/LoginAplicativo?id={operacion.Resultado.Id}");
        //}
        [HttpGet("AppXkaner")]
        [RequiereAcceso]
        public async Task<ActionResult> AppXkaner()
        {
            var operacion = await _loginServicio.ObtenerTokenSesionApp(ObtenerIdUsuarioActual() ?? 0);
            return Redirect($"{_urlConfiguracionDto.UrlEscaner}api/admin/Auth/AppXkaner/{operacion.Resultado.Id}");
        }

        [HttpGet("AppAliados")]
        [RequiereAcceso]
        public async Task<ActionResult> AppAliados()
        {
            var operacion = await _loginServicio.ObtenerTokenSesionApp(ObtenerIdUsuarioActual() ?? 0);
            return Redirect($"{_urlConfiguracionDto.UrlAliadosAdmin}api/administrador/Auth/LoginAplicacion/{operacion.Resultado.Id}");
        }

        [HttpGet("AppTaxiCoolmena")]
        [RequiereAcceso]
        public async Task<ActionResult> AppTaxiCoolmena()
        {
            var operacion = await _loginServicio.ObtenerTokenSesionApp(ObtenerIdUsuarioActual() ?? 0);
            return Redirect($"{_urlConfiguracionDto.UrlTaxiCoolmena}api/admin/Auth/LoginAplicacion/{operacion.Resultado.Id}");
        }

        [HttpGet("AppKme")]
        [RequiereAcceso]
        public async Task<ActionResult> AppKme()
        {
            var operacion = await _loginServicio.ObtenerTokenSesionApp(ObtenerIdUsuarioActual() ?? 0);
            return Redirect($"{_urlConfiguracionDto.UrlKme}api/admin/Auth/LoginAplicacion/{operacion.Resultado.Id}");
        }
    }
}

Orbelite.Erp.SitioWeb/Pages/Admin/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Orbelite.Principal.Seguridad.Datos.Modelo;
using Orbelite.Principal.Seguridad.Datos.Repositorios.Abstracciones;

namespace Orbelite.Erp.SitioWeb.Pages.Admin
{
    public class IndexModel : PageModel
    {
        private readonly IPersonaRepositorio _personaRepositorio;
        public Persona Persona { get; set; }

        public IndexModel(
                           IPersonaRepositorio personaRepositorio
           )
        {

            _personaRepositorio = personaRepositorio;
        }

        public async Task OnGet()
        {
            var claim = HttpContext.User.Claims.SingleOrDefault(m => m.Type == ClaimTypes.NameIdentifier);
            long idUsuario = 0;
            if (claim != null)
            {
                idUsuario = Convert.ToInt64(claim.Value);
            }

            var personaOperacion = await _personaRepositorio.BuscarPorIdUsuarioAsync(idUsuario);
            if (personaOperacion != null)
            {
                Persona = personaOperacion;
            }
                      

        }
    }
}

Orbelite.Erp.SitioWeb/Pages/Admin/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Orbelite.Erp.SitioWeb.Pages.Admin
{
    public class LoginModel : PageModel
    {
        public string UrlDireccionar { get; set; }
        public void OnGet(string ReturnUrl)
        {
            UrlDireccionar = ReturnUrl;
        }
    }
}

Orbelite.Erp.SitioWeb/Pages/Admin/Index.cshtml
@page
@model Orbelite.Erp.SitioWeb.Pages.Admin.IndexModel
@{
}


<input type="hidden" id="__URL_BUSCAR_DATO_PERSONA" value="@Url.Action("DatosUsuario","Auth")" />
<input type="hidden" id="__URL_BUSCAR_DATO_CREDITICIO" value="@Url.Action("Crediticio","Auth")" />
<input type="hidden" id="__URL_BUSCAR_TOTALES" value="@Url.Content($"api/Generales/Vehicular/ConsultarResumen")" />


@section Titulo{
    <div class="d-flex align-items-center flex-wrap mr-1">
        <!--begin::Heading-->
        <div class="d-flex flex-column">
            <!--begin::Title-->
            <h2 class="text-white font-weight-bold my-2 mr-5">Bienvenido</h2>
            <!--end::Title-->
            <!--begin::Breadcrumb-->
            <div class="d-flex align-items-center font-weight-bold my-2">
                <!--begin::Item-->
                <a href="#" class="opacity-75 hover-opacity-100">
                    <i class="flaticon2-shelter text-white icon-1x"></i>
                </a>
                <!--end::Item-->
                <!--begin::Item-->
                <span class="label label-dot label-sm bg-white opacity-75 mx-3"></span>
                <a href="" class="text-white text-hover-white opacity-75 hover-opacity-100">Inicio</a>
                <!--end::Item-->
                <!--begin::Item-->
                <span class="label label-dot label-sm bg-white opacity-75 mx-3"></span>
                <a href="" class="text-white text-hover-white opacity-75 hover-opacity-100">Bienvenido</a>
                <!--end::Item-->
            </div>
            <!--end::Breadcrumb-->
        </div>
        <!--end::Heading-->
    </div>

}


@section Scripts
{
    <script src="~/js/Admin/Index.js?dsgsdf=sdfgf"></script>
}

<input type="hidden" id="__URL_BUSQUEDA" value="@Url.Content("~/api/admin/factura/Factura/UltimosCincoBusqueda")" />
<input type="hidden" id="__URL_DETALLE_FACTURA" value="@Url.Page($"/Admin/Contabilidad/DetalleFacturas")" />



<div class="row">
    <div class="col-xl-12">
        <div class="card card-custom gutter-b">
            <div class="card-body">

                <div class="d-flex">
                    <!--begin: Info-->
                    <div class="flex-grow-1">
                        <!--begin::Title-->
                        <div class="d-flex align-items-center justify-content-between flex-wrap mt-2">
                            <!--begin::User-->
                            <div class="mr-3">
                                <!--begin::Name-->
                                <a href="javascript:void(0);" class="d-flex align-items-center text-dark text-hover-primary font-size-h5 font-weight-bold mr-3">
                                    @if (Model.Persona.IdTipo == 100)
                                    {
                                        @Model.Persona.Nombres @Model.Persona.ApellidoPaterno @Model.Persona.ApellidoMaterno
                                    }
                                    @if (Model.Persona.IdTipo == 101)
                                    {
                                        @Model.Persona.Nombres
                                    }
                                    <i class="flaticon2-correct text-success icon-md ml-2"></i>
                                </a>
                                <!--end::Name-->
                                <!--begin::Contacts-->
                                <div class="d-flex flex-wrap my-2">
                                    <a href="javascript:void(0);" class="text-muted text-hover-primary font-weight-bold mr-lg-8 mr-5 mb-lg-0 mb-2">
                                        <i class="flaticon2-email icon-nm mr-1"></i> @Model.Persona.Correo
                                    </a>
                                    <a href="javascript:void(0);" class="text-muted text-hover-primary font-weight-bold mr-lg-8 mr-5 mb-lg-0 mb-2">
                                        <i class="flaticon2-phone icon-nm mr-1"></i>@Model.Persona.Telefono
                                    </a>
                                    <a href="javascript:void(0);" class="text-muted text-hover-primary font-weight-bold">
                                        <i class="flaticon2-position icon-nm mr-1"></i> @Model.Persona.Direccion |  @Model.Persona.Distrito, @Model.Persona.Provincia, @Model.Persona.Departamento
                                    </a>
                                </div>
                                <!--end::Contacts-->
                            </div>
                            <!--begin::User-->
                            <!--begin::Actions-->
                            <div class="my-lg-0 my-1">
                                <a href="@Url.Page("/Admin/Me/Index")" class="btn btn-sm btn-light-primary font-weight-bolder text-uppercase mr-2">Ver más Información</a>
                            </div>
                            <!--end::Actions-->
                        </div>
                        <!--end::Title-->
                        <!--begin::Content-->
                        <div class="d-flex align-items-center flex-wrap justify-content-between">
                            <!--begin::Description-->
                            <div class="flex-grow-1 font-weight-bold text-dark-50 py-2 py-lg-2 mr-5">
                            </div>
                            <!--end::Description-->
                        </div>
                        <!--end::Content-->
                    </div>
                    <!--end::Info-->
                </div>

            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xl-12">
        <div class="card card-custom gutter-b" id="resultadoTelefonoHtml" @*style="display:none;"*@>
            <div class="card-header">
                <div class="card-title col-12 p-0 d-flex flex-wrap justify-content-between">
                    <h3 class="card-label">Últimas 5 facturas registradas</h3>
                    @*<div class="col-md-2 col-6 p-0">
                            <button class="btn btn-success w-100" id="btnNuevo">Añadir</button>
                        </div>*@
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="text-center table table-separate table-head-custom table-checkable" id="dataTableFactura" style="margin-top: 13px !important">
                        <thead>
                            <tr>
                                <th>Opciones</th>
                                <th>N° Factura</th>
                                <th>Ruc Cliente</th>
                                <th>Razón Social Cliente</th>
                                <th>Fecha Vencimiento</th>
                                <th>Fecha Emisión</th>
                                <th>Moneda</th>
                                <th>IGV</th>
                                <th>SubTotal Ventas</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>