Orbelite.Erp.SitioWeb/Controllers/Admin/MeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Orbelite.Erp.Servicios.Admin.Me.Dtos;
using Orbelite.Principal.Seguridad.Datos.Repositorios.Abstracciones;
using Orbelite.Principal.Seguridad.Servicios.Auth.Servicios.Abstracciones;
using Orbelite.Principal.Seguridad.Servicios.General.Dtos;
using Orbelite.Principal.Seguridad.Servicios.Peticiones.Servicios.Abstracciones;
using Orbelite.Principal.WebComunes.ApiWeb.Auth.Atributos;
using Orbelite.Principal.WebComunes.WebSite.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Orbelite.Erp.SitioWeb.Controllers.Admin
{
    [Route("api/admin/[controller]")]
    [ApiController]
    public class MeController : ControladorBase
    {
        private readonly UrlConfiguracionDto _urlConfiguracionDto;
        private readonly SeguridadConfiguracionDto _seguridadConfiguracionDto;
        private readonly IPeticionServicio _peticionServicio;
        private readonly IPersonaRepositorio _personaRepositorio;
        private readonly IUsuarioServicio _usuarioServicio;
        public MeController(
                             UrlConfiguracionDto urlConfiguracionDto,
                             SeguridadConfiguracionDto seguridadConfiguracionDto,
                             IPeticionServicio peticionServicio,
                             IPersonaRepositorio personaRepositorio,
                             IUsuarioServicio usuarioServicio)
        {
            _urlConfiguracionDto = urlConfiguracionDto;
            _seguridadConfiguracionDto = seguridadConfiguracionDto;
            _peticionServicio = peticionServicio;
            _personaRepositorio = personaRepositorio;
            _usuarioServicio = usuarioServicio;
        }

        [HttpPost("DatosUsuario")]
        [RequiereAcceso]
        public async Task<IActionResult> DatosUsuario()
        {
            var persona = await _personaRepositorio.BuscarPorIdUsuarioAsync((ObtenerIdUsuarioActual() ?? 0));
            var cabecera = new Dictionary<string, string>();
            cabecera.Add("app-name", _seguridadConfiguracionDto.AppName);
            var peticion = _peticionServicio.RealizarJsonPost($"{_urlConfiguracionDto.UrlApiConsultas}api/consultas/Persona/Consulta", new { Dni = persona.Dni }, ObtenerIdUsuarioActual() ?? 0, cabecera);
            return ObtenerResultadoOGenerarErrorDeSimpleRespuestaPeticionWebDto(peticion);
        }

        [HttpPost("HistotrialCrediticio")]
        [RequiereAcceso]
        public async Task<IActionResult> HistotrialCrediticio()
        {
            var persona = await _personaRepositorio.BuscarPorIdUsuarioAsync((ObtenerIdUsuarioActual() ?? 0));
            var cabecera = new Dictionary<string, string>();
            cabecera.Add("app-name", _seguridadConfiguracionDto.AppName);
            var peticion = _peticionServicio.RealizarJsonPost($"{_urlConfiguracionDto.UrlApiFuentes}api/persona/consultas/Sbs/Historial", new { documento = persona.Dni, tipo = (string.IsNullOrWhiteSpace(persona.IdTipo.ToString()) ? 100 : persona.IdTipo) }, ObtenerIdUsuarioActual() ?? 0, cabecera);
            return ObtenerResultadoOGenerarErrorDeSimpleRespuestaPeticionWebDto(peticion);
        }

        [HttpPost("CrediticioDetallePrimero")]
        [RequiereAcceso]
        public IActionResult CrediticioDetallePrimero([FromBody] ConsultarSbsCalificacionDetallePeticionDto parametro)
        {
            var cabecera = new Dictionary<string, string>();
            cabecera.Add("app-name", _seguridadConfiguracionDto.AppName);
            var peticion = _peticionServicio.RealizarJsonPost($"{_urlConfiguracionDto.UrlApiFuentes}api/persona/consultas/Sbs/DetallePrimero", new { id = parametro.Id }, ObtenerIdUsuarioActual() ?? 0, cabecera);
            return ObtenerResultadoOGenerarErrorDeSimpleRespuestaPeticionWebDto(peticion);
        }

        [HttpPost("CrediticioDetalleSegundo")]
        [RequiereAcceso]
        public IActionResult CrediticioDetalleSegundo([FromBody] ConsultarSbsCalificacionDetallePeticionDto parametro)
        {
            var cabecera = new Dictionary<string, string>();
            cabecera.Add("app-name", _seguridadConfiguracionDto.AppName);
            var peticion = _peticionServicio.RealizarJsonPost($"{_urlConfiguracionDto.UrlApiFuentes}api/persona/consultas/Sbs/DetalleSegundo", new { id = parametro.Id }, ObtenerIdUsuarioActual() ?? 0, cabecera);
            return ObtenerResultadoOGenerarErrorDeSimpleRespuestaPeticionWebDto(peticion);
        }

        [HttpPost("CrediticioDetalleTercero")]
        [RequiereAcceso]
        public IActionResult CrediticioDetalleTercero([FromBody] ConsultarSbsCalificacionDetallePeticionDto parametro)
        {
            var cabecera = new Dictionary<string, string>();
            cabecera.Add("app-name", _seguridadConfiguracionDto.AppName);
            var peticion = _peticionServicio.RealizarJsonPost($"{_urlConfiguracionDto.UrlApiFuentes}api/persona/consultas/Sbs/DetalleTercero", new { id = parametro.Id }, ObtenerIdUsuarioActual() ?? 0, cabecera);
            return ObtenerResultadoOGenerarErrorDeSimpleRespuestaPeticionWebDto(peticion);
        }
    }
}

Orbelite.Erp.SitioWeb/Pages/Admin/Me/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Orbelite.Erp.SitioWeb.Pages.Admin.Me
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Orbelite.Erp.SitioWeb/ViewComponents/GoogleMapScript/GoogleMapJavascriptViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Orbelite.Principal.Seguridad.Servicios.General.Dtos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Orbelite.Erp.SitioWeb.ViewComponents.GoogleMapScript
{
    public class GoogleMapJavascriptViewComponent: ViewComponent
    {
        
        private readonly UrlConfiguracionDto _urlConfiguracionDto;
        public GoogleMapJavascriptViewComponent(
                                                UrlConfiguracionDto urlConfiguracionDto)
        {
            _urlConfiguracionDto = urlConfiguracionDto;
        }
        public IViewComponentResult Invoke(int numberOfItems)
        {
            return View("Default", _urlConfiguracionDto.ApiKeyGoogle);
        }
    }
}

Orbelite.Erp.SitioWeb/Pages/Admin/Me/Index.cshtml
@page
@model Orbelite.Erp.SitioWeb.Pages.Admin.Me.IndexModel
@{
}



<input type="hidden" id="__URL_BUSCAR_INFORMACION_PERSONA" value="@Url.Action("DatosUsuario","Me")" />
<input type="hidden" id="__URL_BUSCAR_HISTORIAL_CREDITICIO" value="@Url.Action("HistotrialCrediticio","Me")" />
<input type="hidden" id="__URL_BUSCAR_CREDITICIO_DETALLE_PRIMERO" value="@Url.Action("CrediticioDetallePrimero","Me")" />
<input type="hidden" id="__URL_BUSCAR_CREDITICIO_DETALLE_SEGUNDO" value="@Url.Action("CrediticioDetalleSegundo","Me")" />
<input type="hidden" id="__URL_BUSCAR_CREDITICIO_DETALLE_TERCERO" value="@Url.Action("CrediticioDetalleTercero","Me")" />
<input type="hidden" id="__URL_ACTUALIZAR_DATO_USUARIO" value="@Url.Content($"~/api/admin/Me/ActualizarUsuario")" />
<input type="hidden" id="__URL_ACTUALIZAR_REDES_SOCIALES_USUARIO" value="@Url.Content($"~/api/admin/Me/ActualizarRedesSociales")" />

@section Titulo{
    <div class="d-flex align-items-center flex-wrap mr-1">
        <!--begin::Heading-->
        <div class="d-flex flex-column">
            <!--begin::Title-->
            <h2 class="text-white font-weight-bold my-2 mr-5">Bienvenido</h2>
            <!--end::Title-->
            <!--begin::Breadcrumb-->
            <div class="d-flex align-items-center font-weight-bold my-2">
                <!--begin::Item-->
                <a href="#" class="opacity-75 hover-opacity-100">
                    <i class="icon-2x text-white-50 flaticon2-user"></i>
                </a>
                <!--end::Item-->
                <!--begin::Item-->
                <span class="label label-dot label-sm bg-white opacity-75 mx-3"></span>
                <a href="" class="text-white text-hover-white opacity-75 hover-opacity-100">Mi Perfil</a>
                <!--end::Item-->
                <!--begin::Item-->
                <span class="label label-dot label-sm bg-white opacity-75 mx-3"></span>
                <a href="" class="text-white text-hover-white opacity-75 hover-opacity-100">Bienvenido</a>
                <!--end::Item-->
            </div>
            <!--end::Breadcrumb-->
        </div>
        <!--end::Heading-->
    </div>

}


<div class="card card-custom">
    <!--begin::Header-->
    <div class="card-header card-header-tabs-line">
        <ul class="nav nav-dark nav-bold nav-tabs nav-tabs-line" data-remember-tab="tab_id" role="tablist">

            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#kt_builder_page" role="tab" aria-selected="true">Datos Generales</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="Credicticio-tab" data-toggle="tab" href="#kt_builder_header" role="tab" aria-selected="false">Crediticio</a>
            </li>
        </ul>
    </div>

    <div class="card-body">
        <div class="tab-content pt-3">
            <div class="tab-pane active" id="kt_builder_page">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group row">
                            <label class="col-4 col-form-label">DNI:</label>
                            <div class="col-3">
                                <input class="form-control" type="text" id="txtDni" readonly="readonly" disabled>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-4 col-form-label">Nombres:</label>
                            <div class="col-8">
                                <input class="form-control" type="text" id="txtNombres" readonly="readonly" disabled>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-4 col-form-label">Apellido Paterno:</label>
                            <div class="col-8">
                                <input class="form-control" type="text" id="txtApellidoPaterno" readonly="readonly" disabled>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-4 col-form-label">Apellido Materno:</label>
                            <div class="col-8">
                                <input class="form-control" type="text" id="txtApellidoMaterno" readonly="readonly" disabled>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-4 col-form-label">Fecha de Nacimiento:</label>
                            <div class="col-8">
                                <input class="form-control" type="text" id="txtFechaNacimiento" readonly="readonly" disabled>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-4 col-form-label">Dirección:</label>
                            <div class="col-8">
                                <textarea class="form-control" id="txtDireccion" readonly="readonly" rows="3"></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-4 col-form-label">Distrito:</label>
                            <div class="col-8">
                                <input class="form-control" type="text" id="txtDistrito" readonly="readonly" disabled>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-4 col-form-label">Provincia:</label>
                            <div class="col-8">
                                <input class="form-control" type="text" id="txtProvincia" readonly="readonly" disabled>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-4 col-form-label">Departamento:</label>
                            <div class="col-8">
                                <input class="form-control" type="text" id="txtDepartamento" readonly="readonly" disabled>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div id="map_container_google_direccion" style="height:570px;"></div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="kt_builder_header">
                <div class="form-group row">
                    <div class="col" id="col_1">
                        <div id="lbMes1" class="row justify-content-md-center">
                        </div>

                        <div id="btnColor1" class="row justify-content-md-center">
                        </div>
                    </div>

                    <div class="col" id="col_2">
                        <div id="lbMes2" class="row justify-content-md-center">
                        </div>

                        <div id="btnColor2" class="row justify-content-md-center">
                        </div>
                    </div>

                    <div class="col" id="col_3">
                        <div id="lbMes3" class="row justify-content-md-center">
                        </div>

                        <div id="btnColor3" class="row justify-content-md-center">
                        </div>
                    </div>
                </div>
                <div class="form-group row">

                    <div class="col-xl-12">
                        <div class="table-responsive">
                            <table class="table" id="DataHistorialCrediticio">
                                <thead>
                                    <tr>
                                        <th scope="col">Porcentaje</th>
                                        <th scope="col" class="text-center">Normal</th>
                                        <th scope="col" class="text-center">Problemas Potenciales</th>
                                        <th scope="col" class="text-center">Dudoso</th>
                                        <th scope="col" class="text-center">Deficiente</th>
                                        <th scope="col" class="text-center">Perdidas</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="form-group row">

                    <div class="col-xl-12">
                        <div class="table-responsive">
                            <table class="table" id="tableDatalleHistorial">
                                <thead>
                                    <tr>
                                        <th scope="col">Entidad</th>
                                        <th scope="col">Tipo Moneda</th>
                                        <th scope="col">Monto</th>
                                        <th scope="col">Días Vencidos</th>
                                        <th scope="col">Calificación</th>
                                        <th scope="col">Descripción</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>

@await Component.InvokeAsync("GoogleMapJavascript")

<script src="~/js/Admin/Me/Index.js?v=1.2.5"></script>